### ISSUE TITLE
When a user deletes their sandbox it remains in the public workflow gallery 

### ISSUE THREAD

**Issue by annias** [eg9y/promptsandbox.io#6]
- When a user deletes their sandbox it remains in the public workflow gallery even though it’s deleted and not in their sandbox list anymore, hence the gallery will be getting filled with junk and deleted workflows.

**Comment by eg9y** [comment]
This is probably because of the caching logic in the getWorkflows api. It would generate a cached response for every 14400 seconds, which is  240 minutes. Maybe we can decrease the duration?

https://github.com/eg9y/promptsandbox.io/blob/fd5ee108d7573b9d0f96e90d0d4c8fe8910899fb/api/getWorkflows.ts#L35

**Comment by spankyed** [comment]
I don't know much about cache control. But to me, a cache of two minutes seems reasonable for a public gallery. Two hours seems like much.

**Comment by eg9y** [comment]
Makes sense, I'll change it to 2 mins

**Comment by eg9y** [comment]
Made commit 20cacca4a7474ef797021a221ec9b2f1716f0c4d
Closing this issue. Thank you!
